name: 'Lint Helm Chart'
description: 'Lints the helm charts'
inputs:
  CHARTS_DIR:
    description: 'The filename of the helm chart to be linted'
    type: string
    required: true
  CHECK_VERSION_INCREMENT:
    description: 'If the version increment should be checked'
    type: bool
    required: true
  CHECK_MAINTAINERS:
    description: 'The filename of the helm chart to be linted'
    type: bool
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Set up Helm
    uses: azure/setup-helm@v3
    with:
      version: v3.12.1
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10'
      check-latest: true
  - name: Set up chart-testing
    uses: helm/chart-testing-action@v2.6.0
  - name: Run chart-testing (lint)
    shell: bash
    run: ct lint \
          --charts ${{ inputs.CHARTS_DIR }} \
          --check-version-increment ${{ CHECK_VERSION_INCREMENT}}
          --check-maintainers ${{ CHECK_MAINTAINERS }}
