name: 'Lint Helm Chart'
description: 'Lints the helm charts'
inputs:
  CHARTS_DIR:
    description: 'The filename of the helm chart to be linted'
    type: string
    required: true
  CHECK_VERSION_INCREMENT:
    description: 'If the version increment should be checked'
    type: bool
    required: true
  VALIDATE_MAINTAINERS:
    description: 'The filename of the helm chart to be linted'
    type: bool
    required: true
runs:
  using: "composite"
  steps:
  - name: Run chart-testing (lint)
    shell: bash
    run: ct lint \
          --charts ${{ inputs.CHARTS_DIR }} \
          --check-version-increment=${{ CHECK_VERSION_INCREMENT}}
