name: 'Lint Helm Chart'
description: 'Lints the helm charts'
inputs:
  CHARTS:
    description: 'The filename(s) of the helm chart to be linted'
    type: string
    required: true
  CHECK_VERSION_INCREMENT:
    description: 'If the version increment should be checked'
    type: bool
    required: true
  VALIDATE_MAINTAINERS:
    description: 'If the existence and validity of maintainers should be checked'
    type: bool
    required: true
runs:
  using: "composite"
  steps:
  - name: Run chart-testing (lint)
    shell: bash
    run: ct lint \
          --charts ${{ inputs.CHARTS }} \
          --check-version-increment=${{ CHECK_VERSION_INCREMENT}} \
          --validate-maintainers=${{ VALIDATE_MAINTAINERS }}
