name: 'Lint Helm Chart'
description: 'Lints the helm charts'
inputs:
  TARGET_BRANCH:
    description: "The branch name to be linted (required to overrride the default 'master')"
    type: string
    required: false
    default: main
  CHARTS:
    description: 'The filename(s) of the helm chart to be linted'
    type: string
    required: true
  CHECK_VERSION_INCREMENT:
    description: 'If the version increment should be checked'
    type: bool
    required: true
  VALIDATE_MAINTAINERS:
    description: 'If the existence and validity of maintainers should be checked'
    type: bool
    required: true
runs:
  using: "composite"
  steps:
  - name: Run chart-testing (lint)
    shell: bash
    run: ct lint \
          --target-branch ${{ TARGET_BRANCH }}
          --charts ${{ inputs.CHARTS }} \
          --check-version-increment ${{ inputs.CHECK_VERSION_INCREMENT}} \
          --validate-maintainers ${{ inputs.VALIDATE_MAINTAINERS }}
