name: 'Lint Helm Chart'
description: 'Lints the helm charts'
inputs:
  DOCKERFILE:
    description: 'The filename of the helm chart to be linted'
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Set up Helm
    uses: azure/setup-helm@v3
    with:
      version: v3.12.1
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10'
      check-latest: true
  - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.0
  - name: Run chart-testing (lint)
    run: ct lint --target-branch ${{ github.event.repository.default_branch }}
