name: 'Config Test'
description: Tests stuff
inputs:
  ATOMIC:
    description: "Use --atomic flag. If set, the upgrade process rolls back changes made in case of failed upgrades."
    required: false
    default: true

runs:
  using: "composite"
  steps:
  - name: Debug ATOMIC value
    shell: bash
    run: "echo ATOMIC: ${{ inputs.ATOMIC }}"
  - name: Debug ATOMIC value2
    shell: bash
    run: "echo ATOMIC-Flag: ${{ inputs.ATOMIC && '--atomic' || '' }}"
  - name: Debug ATOMIC value3
    shell: bash
    run: |-
      ls \
        -l \
        ${{ inputs.ATOMIC == 'true' && '-a' || '' }}