apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  myvalue: "Hello World"
  myval2: "as"
  domains: |
    {{- range $subdomain := .Values.subdomains }}
      {{ if eq $.Values.env.stage "prod" }}
        - {{ $subdomain }}.bergfreunde.de
      {{ else }}
        - {{ $subdomain }}.{{ $.Values.env.prefix }}.bergfreunde.de
      {{ end }}
    {{- end }}