
name: Lint and Test Charts

on:
  - push
  - workflow_dispatch

jobs:
  lint-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

          