
name: Testing

on:
  workflow_dispatch:
    inputs:
      myEnv:
        type: environment
        required: true
        default: dev-

jobs:
  example:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    environment: ['dev-01', 'dev-02', 'dev-03']
    #  fail-fast: true
    steps:
    - run: echo "Test on ${{ inputs.myEnv }}"
    - run: sleep 10
      timeout-minutes: 1
      id: bad
      continue-on-error: true
    - run: echo "Ok"
      if: job.steps.bad.status == failure()
  #example-two:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      environment: ['dev-01', 'dev-02', 'dev-03']
  #    fail-fast: true
  #  steps:
  #  - run: echo "Hi from ${{ matrix.environment }}"
  #    if: ${{ matrix.environment == inputs.myEnv}}