
name: Testing

on:
  workflow_dispatch:
    inputs:
      #env:
      #  type: environment
      #  required: true
      #  default: dev-
      env:
        type: choice
        required: true
        options:
          - dev-01
          - dev-02
          - dev-03

jobs:
  #env-select:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      environment: ${{ fromJSON(vars.DEV_SYSTEMS) }}
  #    fail-fast: true
  #  environment: ${{ matrix.environment }}
  #  steps:
  #  - run: echo "Test on ${{ matrix.environment }}"
  wf-select:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - run: "Test on ${{ inputs.env }}"
  
  build-push-deploy:
    runs-on: ubuntu-latest
    needs: wf-select
    environment: ${{ inputs.env }}
    steps:
      - run: echo "Build Push Deploy on ${{ inputs.env }}"