
name: Testing

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: dev-

jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['dev-01', 'dev-02']
      fail-fast: true
      max-parallel: 1
    steps:
    - run: echo "Test on ${{ matrix.environment }}"
    - run: sleep 100
      timeout-minutes: 1
      id: bad
      continue-on-error: true
    - run: echo "OK"
      if: job.steps.bad.status == failure()