
name: Testing

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Test"
    - run: exit 1
      id: bad
      continue-on-error: true
    - run: echo "OK"
      if: job.steps.bad.status == failure()